version: '3'

services:

  web:
    build: ./docker-files/
    ports:
      - 8080:80
    volumes:
      - /Users/yamazato/Sites/nuocw-mdfile-generator:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - /Users/yamazato/Sites/nuocw-mdfile-generator/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d