version: '3'

services:

  web:
    build: ./docker-files/
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d